### PR TITLE
project. Sorry for the late pull request

### PR DESCRIPTION
**Pull request by JaneRuby**

### CODE REVIEW

**Comment by charlesdrews** [comment]
I don't see a commit adding AsyncTask(s), so I'll have to mark the Threading Homework incomplete

**Comment by charlesdrews** [comment]
#### Performance Evaluation

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria | X | | |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like | | | X |
| Use relationships (joins) between tables | X | | |
| Use the database as the data provider for search results | | X | |
| Allow the user to add products to a shopping cart, which they can view at any time | | | X |
| Incorporate Object Oriented principles into your app | | X | |
| Contain code comments, explaining the functionality behind sections of code | | X | |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end | | X | |
| Include espresso tests for your app | X | | |


| **Bonus** | Complete |
|---|---|
| An entity relationship diagram (ERD) that defines how your app's data is modeled | - |
| Using your ERD as a guideline, implement the classes required for your app | - |
| Incorporate Material Design principles into your app | - |
| Create a review system for user feedback for each product | - |
| Add more complexity to the user's searches (e.g. more than one search criteria at a time) | - |
| Add JUnit tests for your non-Android classes | - |
| Incorporate Glide or Picasso | X |

Notes:

You were on the right track with some features, but unfortunately you missed the mark on some of the requirements. One big issue right off the bat was that your code to populate the database with products was commented out, so the database was empty and there was nothing for me to view. I had to go in your code and un-comment that code before I could see anything.

The search functionality is missing. There is a problem with the manifest (wrong `name` value in the meta-data tag; should be `android.app.searchable`), but even if that's corrected and the `onNewIntent()` method in MainActivity actually runs, it still doesn't do anything with the data returned by the database. You get a cursor of search results on line 166, but it is never used. Also, you setup the RecyclerView all over again there - the idea is to set it up once in `onCreate()` then later just update the data used by the adapter and call one of the `notify...()` methods on the adapter. Recreating all those things each time is very memory inefficient.

Your product entries show up in the grid, but on the emulator they all overlap each other. Make sure you always test on both large and small devices to ensure your layouts aren't dependent on a particular screen size.

Also, I see that you included a join in one of your database helper methods, but that method is never used, and the join query doesn't really make sense - it's joining a table with itself, which is not necessary. The whole idea of a join is to pull in data from multiple tables.

Because your project falls short of the minimum standards, you will need to update it to meet more of the requirements before it can be considered complete. _**Do you think you can update your app to meet most of the requirements by Monday, 8/15?**_ If not, please let us know ASAP so we can determine an alternate timeline.

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **8**

**Comment by charlesdrews** [comment]
When I gave your detailed feedback, I asked if you could re-submit the project with more features implemented by 8/15. You did not respond or re-submit. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a **hard deadline of Wednesday, 8/24** to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

**Comment by JaneRuby** [comment]
I had slack responded to you. And you said to worry about the group project for this week and I could do the project redo when the group project was over... Is that the same conversation you are referring to? I am pretty sure I can do the redo by that date.... :)

**Comment by charlesdrews** [comment]
Sorry; you did indeed slack me about that. But I sent the original feedback on 8/8 asking you to re-submit by 8/15, and you did not slack me about it until after 5pm on 8/12, meaning 4 days that could have been spent revising project 2 were lost.

Regardless, please meet the 8/24 cutoff so that you stay on track to meet outcomes support. Also, your completion % has dropped to 80%, which is right at the threshold. Please keep this in mind and be sure to keep that % up during unit 4!

**Comment by JaneRuby** [comment]
I think that I should be able to meet the 8/24 cutoff. I am still dealing with my own health issues right now, so I hope that will not affect me catching up on missing work and finished the project redo. Working on project 3 has definitely helped me learn about what i need to fix for project 2. I really appreciate your understanding regarding everything.

**Pull request closed without merging**
