### PR TITLE
Still a work in progress

### PR DESCRIPTION
**Pull request by jchan1990**

### CODE REVIEW

**Comment by charlesdrews** [comment]
I don't see any commits adding AsyncTask(s), so I'll have to mark the Threading Homework incomplete

**Comment by jchan1990** [comment]
Use the Project 2 simple shop instead

**Comment by charlesdrews** [comment]
#### Performance Evaluation

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria | X | | |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like | | | X |
| Use relationships (joins) between tables | X | | |
| Use the database as the data provider for search results | X | | |
| Allow the user to add products to a shopping cart, which they can view at any time | X | | |
| Incorporate Object Oriented principles into your app | | X | |
| Contain code comments, explaining the functionality behind sections of code | | X | |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end | | X | |
| Include espresso tests for your app | X | | |


| **Bonus** | Complete |
|---|---|
| An entity relationship diagram (ERD) that defines how your app's data is modeled | - |
| Using your ERD as a guideline, implement the classes required for your app | - |
| Incorporate Material Design principles into your app | - |
| Create a review system for user feedback for each product | - |
| Add more complexity to the user's searches (e.g. more than one search criteria at a time) | - |
| Add JUnit tests for your non-Android classes | - |
| Incorporate Glide or Picasso | - |

Notes:

You're on the right track with some features, but unfortunately most of the features missed the mark.

The search features currently doesn't work, but you're close - take another look at your SQL query string that uses the user's input (lines 407-408 in DB_Helper) to make sure they use the LIKE keyword and the % wildcard properly. Then set up the ListView to show the results.

You are also missing the cart. As we discussed, this will be a good opportunity to incorporate a join in a query in your database helper. If you implement the search and cart functions, you should be in good shape for this project.

As discussed, your project does not currently meet minimum standards. You will need to implement more of the requirements before it can be considered complete. _**Do you think you can complete most of the requirements by Monday, 8/15?**_ If that does not seem feasible, please let us know ASAP.

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **5**

**Comment by charlesdrews** [comment]
When I gave your detailed feedback, I asked if you could re-submit the project with more features implemented by 8/15. You did not respond or re-submit. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a **hard deadline of Wednesday, 8/24** to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

**Comment by jchan1990** [comment]
Hi Charlie
I understand and I thought I updated the app I think I still need to fix up
the search and shopping cart

**Comment by charlesdrews** [comment]
Thank you for responding. Please meet the 8/24 cutoff so you stay on track to receive outcomes support. Also, your completion % has dropped to 80%, which is right at the threshold. Please don't let it dip any lower!

**Comment by jchan1990** [comment]
I was talking to Alan and I was wondering if I can meet Liz the new
learning helper?

**Comment by charlesdrews** [comment]
Sure, we can schedule something next week

**Comment by jchan1990** [comment]
Thanks Charlie I appreciate everything you're doing!

**Pull request closed without merging**
