### PR TITLE
Didn't finish everything and right now all the data is the same

### PR DESCRIPTION
**Pull request by StacyZol**

### CODE REVIEW

**Comment by StacyZol** [comment]
I guess I closed it as soon as I made the pull request. Not sure how, but that was a mistake.

**Comment by charlesdrews** [comment]
I'll have to mark the Threading Homework incomplete since you haven't added any AsyncTasks yet, but hopefully after seeing some more examples in class these are getting clearer. Let me know if you need to go over them some more.

**Comment by drew-mahrt** [comment]
#  RUBRIC
## Project 2 | Mobile Commerce App 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria | |x | |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like |x | | |
| Use relationships (joins) between tables |x | | |
| Use the database as the data provider for search results | | |x |
| Allow the user to add products to a shopping cart, which they can view at any time | | |x |
| Incorporate Object Oriented principles into your app | | | x|
| Contain code comments, explaining the functionality behind sections of code | |x | |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end | | | x|
| Include espresso tests for your app |x | | |


| **Bonus** | Complete |
|---|---|
| An entity relationship diagram (ERD) that defines how your app's data is modeled |  |
| Using your ERD as a guideline, implement the classes required for your app |  |
| Incorporate Material Design principles into your app |  |
| Create a review system for user feedback for each product |  |
| Add more complexity to the user's searches (e.g. more than one search criteria at a time) |  |
| Add JUnit tests for your non-Android classes |  |
| Incorporate Glide or Picasso |  |

Notes:

You had a good start, and have most of your functionality complete, there are just some bugs here and there with some core functionality. You have most of the code in place for search, but it isn't working. Also, you had a few comments, but there needs to be more that describe what some of your methods are doing, and what the purpose of some of your classes are.

I feel like this project contains files from two completely separate apps. Were you originally starting with something related to clothing, and then moved to something else? Make sure you delete the files that aren't really a part of your app anymore.

Since search is a primary feature of this assignment, I would like you to take some extra time to finish it. Keep working on the app, and turn in an updated version by Weds, 8/24. Let me know if you have any questions.

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **10**

**Comment by charlesdrews** [comment]
I am following up Drew's request that you re-submit this project with more features implemented. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a **hard deadline of Wednesday, 8/24** to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

**Pull request closed without merging**
