### PR TITLE
Project-2---Ecommerce-Mobile-App - Wan Lim

### PR DESCRIPTION
**Pull request by wanaaaa**

### CODE REVIEW

**Comment by wanaaaa** [comment]
image can be save in web and retrieved by picasso..

**Comment by charlesdrews** [comment]
👍 threading homework done - I see the AsyncTask you added

However, you returned the data from `doInBackground()` but you don't have an `onPostExecute()` method which does anything with the data back on the UI thread.

**Comment by drew-mahrt** [comment]
#  RUBRIC
## Project 2 | Mobile Commerce App 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria | | | x|
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like | | |x |
| Use relationships (joins) between tables |x | | |
| Use the database as the data provider for search results | | |x |
| Allow the user to add products to a shopping cart, which they can view at any time | | | x|
| Incorporate Object Oriented principles into your app | | | x|
| Contain code comments, explaining the functionality behind sections of code | |x | |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end |x | | |
| Include espresso tests for your app |x | | |


| **Bonus** | Complete |
|---|---|
| An entity relationship diagram (ERD) that defines how your app's data is modeled |  |
| Using your ERD as a guideline, implement the classes required for your app |  |
| Incorporate Material Design principles into your app |  |
| Create a review system for user feedback for each product |  |
| Add more complexity to the user's searches (e.g. more than one search criteria at a time) |  |
| Add JUnit tests for your non-Android classes |  |
| Incorporate Glide or Picasso |  |

Notes:

I graded the 001 copy of the project since the threading version wouldn't compile.

After reviewing your project, you seemed to be on the right track. Your products table in your database was set up and working correctly. However, you were missing some core functionality  in terms of having multiple tables, and your shopping cart was working, but sloppy.

One small fix I would like to see you make is to add some additional comments to your code so I can give you full points for that. With that change, your grade will increase to 12/18 which is the minimum passing score. Please have this done by August 24th.

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **11**

**Comment by charlesdrews** [comment]
I am following up Drew's request that you re-submit this project with more features implemented. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a **hard deadline of Wednesday, 8/24** to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

**Comment by wanaaaa** [comment]
I understand it.
Thanks

**Pull request closed without merging**
