### PR TITLE
Dave Stone Project 2 ... Pretty Far Along... but not quite there

### PR DESCRIPTION
**Pull request by davidhstone**

### CODE REVIEW

**Comment by charlesdrews** [comment]
I don't see a commit adding AsyncTask(s), so I'll have to mark the Threading Homework incomplete

**Comment by drew-mahrt** [comment]
#  RUBRIC
## Project 2 | Mobile Commerce App 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria | | x| |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like |x | | |
| Use relationships (joins) between tables |x | | |
| Use the database as the data provider for search results | | |x |
| Allow the user to add products to a shopping cart, which they can view at any time | | |x |
| Incorporate Object Oriented principles into your app | | | x|
| Contain code comments, explaining the functionality behind sections of code | |x | |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end | x| | |
| Include espresso tests for your app |x | | |


| **Bonus** | Complete |
|---|---|
| An entity relationship diagram (ERD) that defines how your app's data is modeled |  |
| Using your ERD as a guideline, implement the classes required for your app |  |
| Incorporate Material Design principles into your app |  |
| Create a review system for user feedback for each product |  |
| Add more complexity to the user's searches (e.g. more than one search criteria at a time) |  |
| Add JUnit tests for your non-Android classes |  |
| Incorporate Glide or Picasso |  |

Notes:

You had a strong start on this project. Your database is set up nicely, and you had the search method ready, but never got it actually working. Also, you got part way there on the commenting, but you could do with removing some of the code you no longer need. Add more comments that explain what the current code does rather than explaining what the code that should be deleted does.

The minimum score for passing this project is a 12/18. See if you can continue working on it to bring up your score by Weds 8/24. Use the rubric as a guide for making sure you complete the requirements that will earn you additional points. Let me know if you have any questions.

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **8**

**Comment by charlesdrews** [comment]
I am following up Drew's request that you re-submit this project with more features implemented. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a **hard deadline of Wednesday, 8/24** to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

**Comment by davidhstone** [comment]
yup. I'd responded the same to his message on Slack upon reading it several
days ago

**Pull request closed without merging**
