### PR TITLE
Jordan Goldberg Project-2 Scheme Dreams 7/29

### PR DESCRIPTION
**Pull request by jord-goldberg**

### CODE REVIEW

**Comment by charlesdrews** [comment]
I know you worked on adding AsyncTasks, but I don't see any commits with that code, so I'll have to mark the Threading Homework incomplete until I see that code

**Comment by jord-goldberg** [comment]
Now with Espresso tests and Async tasks

**Comment by charlesdrews** [comment]
👍 Threading HW complete (I see the AsyncTasks you added for your database calls)

**Comment by alanjcaceres** [comment]
| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria | | X| |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like | | | X |
| Use relationships (joins) between tables | | X|  |
| Use the database as the data provider for search results | | | X |
| Allow the user to add products to a shopping cart, which they can view at any time | | | X |
| Incorporate Object Oriented principles into your app | | | X |
| Contain code comments, explaining the functionality behind sections of code | | | X |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end | | | X |
| Include espresso tests for your app | | X | |

---

### Max Points : 18
### Points Earned : 15

---
Great job Jordan.
Excellent use of object oriented programming.
When including strings, it is best practice to place them as a resource instead of in your Java code.

**Pull request closed without merging**
