### PR TITLE
Operational Mobile App

### PR DESCRIPTION
**Pull request by raymour123**

### CODE REVIEW

**Comment by charlesdrews** [comment]
I don't see a commit adding AsyncTask(s), so I'll have to mark the Threading Homework incomplete

**Comment by drew-mahrt** [comment]
#  RUBRIC
## Project 2 | Mobile Commerce App 	 						


#### Performance Evaluation
> Mark boxes with an 'X'; if did not achieve bonus, mark with a '-'

| Requirements | Incomplete (0) | Does Not Meet Expectations (1) | Meets Expectations (2) |
|---|---|---|---|
| Allow the user to search by product-related criteria |x | | |
| Show results in separate entries/pages to the user, including descriptions, images, and whatever else you like | x| | |
| Use relationships (joins) between tables | x| | |
| Use the database as the data provider for search results |x | | |
| Allow the user to add products to a shopping cart, which they can view at any time | | | x|
| Incorporate Object Oriented principles into your app | | | x|
| Contain code comments, explaining the functionality behind sections of code |x | | |
| Include **at least 4** user stories - the app must be able to complete all 4 user stories from beginning to end |x | | |
| Include espresso tests for your app |x | | |


| **Bonus** | Complete |
|---|---|
| An entity relationship diagram (ERD) that defines how your app's data is modeled |  |
| Using your ERD as a guideline, implement the classes required for your app |  |
| Incorporate Material Design principles into your app |  |
| Create a review system for user feedback for each product |  |
| Add more complexity to the user's searches (e.g. more than one search criteria at a time) |  |
| Add JUnit tests for your non-Android classes |  |
| Incorporate Glide or Picasso |  |

Notes:

You have a really good start to this. Your product catalog looks great, and your database is set up nicely, but you're missing the core functionality for search, and the points for adding comments are easy to get.

Continue working on this so you can get enough points to get a passing grade. See what you can do by 8/24, and make another pull request. Let me know if you have any questions.

---

## Score:
Based on the requirements, you can earn a maximum of  **18**  points on this project.

#### Your total score is: **4**

**Comment by charlesdrews** [comment]
I am following up Drew's request that you re-submit this project with more features implemented. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a **hard deadline of Wednesday, 8/24** to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

**Comment by raymour123** [comment]
Yes I definitely understand, I'll be solely working on this over the weekend.

Get Outlook for Android<https://aka.ms/ghei36>



On Thu, Aug 18, 2016 at 4:32 PM -0400, "Charles Drews" <notifications@github.com<mailto:notifications@github.com>> wrote:


I am following up Drew's request that you re-submit this project with more features implemented. As a reminder, students must complete ALL projects in order to complete the course and receive outcomes support. We need to set a hard deadline of Wednesday, 8/24 to re-submit a version of this project that meets minimum standards. Please respond to this comment so I know you understand.

-

**Comment by charlesdrews** [comment]
Thank you for responding. Your project 1 is in a similar situation - I will be sending a separate comment on that, but it will be the same 8/24 deadline.

I also want to remind you that your completion % is well below the 80% threshold at 68%. Please do what you can to submit some past assignments to bring that up. We may also need to meet with the learning coach Lizzie next week to discuss what to do if it become mathematically impossible for you to hit the 80% threshold.

**Pull request closed without merging**
